# Use `-v <host_path>:<container_path>` to mount local(host) direcotry to container
# For example: 
#   docker run -i -t -v d:\Docker\shared\:/root/dev/ astra-dev

FROM debian:10-slim
LABEL author="idma88"

ENV DISPLAY=host.docker.internal:0

COPY script/* /var/local/deb/
RUN cd /var/local/deb/ && ./install.sh

CMD [ "/bin/bash" ]