FROM alpine

LABEL author="idma88"
LABEL version="1.0"

# Add param to start `-v <host_folder>:/<folder>` for share up/download files

RUN apk add telegram-desktop && \
rm -rf /var/cache/apk/* /tmp

# RUN mkdir /download
# VOLUME /download

# Make sure to enable "Use system frame"
CMD if [ ! -f tg_conf_done ]; then touch tg_conf_done && ${TG_APP} -tosettings; else ${TG_APP}; fi

ENV DISPLAY=host.docker.internal:0
ENV TG_APP=telegram-desktop